network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enP3p49s0:
      dhcp4: no
      addresses:
        - 192.168.0.100/24
      routes:
        - to: default
          via: 192.168.0.1
          metric: 100
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
    enP4p65s0:
      dhcp4: no
      addresses:
        - 192.168.254.100/24
      routes:
        - to: default
          via: 192.168.254.1
          metric: 200
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      
